
# Directories
DATA_DIR: "data"
RAW_DIR: "raw"
PROCESSED_DIR: "processed"
MODEL_DIR: "models"

# Data files
RAW_DATA_FILENAME: "churn_bank.csv"
TRAIN_DATA_FILENAME: "train.csv"
TEST_DATA_FILENAME: "test.csv"

# Artifacts
PREPROCESSOR_FILENAME: "preprocessor.joblib"
MODEL_FILENAME: "best_model.joblib"
METRICS_FILENAME: "metrics.json"
ACTIVE_MODEL_FILENAME: "active_model.joblib"

# Model/Feature Parameters
TEST_SIZE: 0.25
RANDOM_STATE: 42

TARGET_COLUMN: "Exited"
NUMERICAL_FEATURES : ['CreditScore', 'Age', 'Balance', 'EstimatedSalary',]
CATEGORICAL_FEATURES: ['Geography','Gender',]
PRE_ENCODED_FEATURES: ['NumOfProducts','HasCrCard','IsActiveMember','Tenure',]

# Model Selection Metrics
MODEL_SELECTION_METRIC: "f1_score"  # accuracy | precision | recall | f1_score


# Model & Hyperparameters
MODELS:

  logistic_regression:
    enabled: true
    params:
      penalty: "l2"
      C: 1.0
      solver: "lbfgs"
      max_iter: 1000
      class_weight: "balanced"
  
  random_forest:
    enabled: true
    params:
      n_estimators: 200
      max_depth: 10
      min_samples_split: 5
      min_samples_leaf: 2
      class_weight: "balanced"
      n_jobs: -1
    
  gradient_boosting:
    enabled: true
    params:
      n_estimators: 200
      learning_rate: 0.05
      subsample: 0.8
  
  xgboost:
    enabled: true
    params:
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 4
      subsample: 0.8
      colsample_bytree: 0.8
      eval_metric: "logloss"
      use_label_encoder: false
    
  adaboost:
    enabled: false
    params:
      n_estimators: 200
      learning_rate: 0.05
  
  decision_tree:
    enabled: false
    params:
      max_depth: 5
      min_samples_split: 10
      min_samples_leaf: 4
      class_weight: "balanced"